version: 3

tasks:
  protos:
    aliases:
      - proto
    desc: "Generate from proto file"
    cmds:
      - protoc -I ./proto auth.proto --go_out=gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative